### ISSUE TITLE
error while building audio.primary.msm7x27a

### ISSUE THREAD

**Issue by sunnyden** [SlimLP-Y300/android_device_huawei_u8825#1]
i just trying to port cm12 to my c8812e,whose hardware is nearly the same as u8825.i have already successfully port cm11 to my device.but this time something wrong happened,while building the audio HAL.
the log is here:
the error log is:

---

device/huawei/c8812e/audio/AudioHardware.cpp:312:70: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioStreamOutDirect'
                 AudioStreamOutDirect\* out = new AudioStreamOutDirect();
                                                                      ^
device/huawei/c8812e/audio/AudioHardware.cpp:350:114: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioSessionOutLPA'
             AudioSessionOutLPA\* out = new AudioSessionOutLPA(this, devices, _format, *channels,_sampleRate,0,&err);
                                                                                                                  ^
device/huawei/c8812e/audio/AudioHardware.cpp:372:68: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioStreamOutMSM72xx'
             AudioStreamOutMSM72xx\* out = new AudioStreamOutMSM72xx();
                                                                    ^

---

chil,i don't know what cause this issue,could you please help me to find out what's wrong ? thank you so much!

---

the full log is here:
target thumb C++: audio.primary.msm7x27a <= device/huawei/c8812e/audio/AudioHardware.cpp
target thumb C++: audio.primary.msm7x27a <= device/huawei/c8812e/audio/audio_hw_hal.cpp
In file included from device/huawei/c8812e/audio/audio_hw_hal.cpp:24:0:
system/core/include/system/audio.h:901:1: warning: missing initializer for member 'audio_offload_info_t::bit_width' [-Wmissing-field-initializers]
 };
 ^
system/core/include/system/audio.h:901:1: warning: missing initializer for member 'audio_offload_info_t::use_small_bufs' [-Wmissing-field-initializers]
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:71:0: warning: "SRS_DISABLE" redefined [enabled by default]
 #define SRS_DISABLE 0xFFDF
 ^
In file included from device/huawei/c8812e/audio/AudioHardware.h:32:0,
                 from device/huawei/c8812e/audio/AudioHardware.cpp:35:
/media/sunny/Android/L/out/target/product/c8812e/obj/KERNEL_OBJ/usr/include/linux/msm_audio.h:140:0: note: this is the location of the previous definition
 #define SRS_DISABLE 0x0040
 ^
In file included from device/huawei/c8812e/audio/audio_hw_hal.cpp:27:0:
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:129:25: warning: unused parameter 'observer' [-Wunused-parameter]
     virtual int         setObserver(void _observer)  {return INVALID_OPERATION;}
                         ^
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:130:25: warning: unused parameter 'buf' [-Wunused-parameter]
     virtual status_t    getBufferInfo(buf_info *_buf) {return INVALID_OPERATION;}
                         ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:132:12: warning: unused parameter 'rate' [-Wunused-parameter]
 static int out_set_sample_rate(struct audio_stream _stream, uint32_t rate)
            ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:163:12: warning: unused parameter 'format' [-Wunused-parameter]
 static int out_set_format(struct audio_stream *stream, audio_format_t format)
            ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:304:12: warning: unused parameter 'stream' [-Wunused-parameter]
 static int out_add_audio_effect(const struct audio_stream *stream, effect_handle_t effect)
            ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:304:12: warning: unused parameter 'effect' [-Wunused-parameter]
device/huawei/c8812e/audio/audio_hw_hal.cpp:309:12: warning: unused parameter 'stream' [-Wunused-parameter]
 static int out_remove_audio_effect(const struct audio_stream *stream, effect_handle_t effect)
            ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:309:12: warning: unused parameter 'effect' [-Wunused-parameter]
device/huawei/c8812e/audio/audio_hw_hal.cpp:330:12: warning: unused parameter 'rate' [-Wunused-parameter]
 static int in_set_sample_rate(struct audio_stream *stream, uint32_t rate)
            ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:361:12: warning: unused parameter 'format' [-Wunused-parameter]
 static int in_set_format(struct audio_stream *stream, audio_format_t format)
            ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:534:12: warning: unused parameter 'handle' [-Wunused-parameter]
 static int adev_open_output_stream(struct audio_hw_device *dev,
            ^
device/huawei/c8812e/audio/audio_hw_hal.cpp:608:12: warning: unused parameter 'handle' [-Wunused-parameter]
 static int adev_open_input_stream(struct audio_hw_device *dev,
            ^
In file included from hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareBase.h:20:0,
                 from device/huawei/c8812e/audio/AudioHardware.h:29,
                 from device/huawei/c8812e/audio/AudioHardware.cpp:35:
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:129:25: warning: unused parameter 'observer' [-Wunused-parameter]
     virtual int         setObserver(void *observer)  {return INVALID_OPERATION;}
                         ^
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:130:25: warning: unused parameter 'buf' [-Wunused-parameter]
     virtual status_t    getBufferInfo(buf_info *_buf) {return INVALID_OPERATION;}
                         ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:304:29: warning: unused parameter 'left' [-Wunused-parameter]
         virtual status_t    setVolume(float left, float right) { return INVALID_OPERATION; }
                             ^
device/huawei/c8812e/audio/AudioHardware.h:304:29: warning: unused parameter 'right' [-Wunused-parameter]
device/huawei/c8812e/audio/AudioHardware.h:338:29: warning: unused parameter 'left' [-Wunused-parameter]
         virtual status_t    setVolume(float left, float right) { return INVALID_OPERATION; }
                             ^
device/huawei/c8812e/audio/AudioHardware.h:338:29: warning: unused parameter 'right' [-Wunused-parameter]
device/huawei/c8812e/audio/AudioHardware.h:525:29: warning: unused parameter 'gain' [-Wunused-parameter]
         virtual status_t    setGain(float gain) { return INVALID_OPERATION; }
                             ^
device/huawei/c8812e/audio/AudioHardware.h:573:29: warning: unused parameter 'gain' [-Wunused-parameter]
         virtual status_t    setGain(float gain) { return INVALID_OPERATION; }
                             ^
device/huawei/c8812e/audio/AudioHardware.h: In constructor 'android_audio_legacy::AudioHardware::AudioHardware()':
device/huawei/c8812e/audio/AudioHardware.h:630:25: warning: 'android_audio_legacy::AudioHardware::mTtyMode' will be initialized after [-Wreorder]
             int         mTtyMode;
                         ^
device/huawei/c8812e/audio/AudioHardware.h:611:37: warning:   'android_audio_legacy::AudioHardware::AudioStreamOutMSM72xx\* android_audio_legacy::AudioHardware::mOutput' [-Wreorder]
             AudioStreamOutMSM72xx\*  mOutput;
                                     ^
device/huawei/c8812e/audio/AudioHardware.cpp:151:1: warning:   when initialized here [-Wreorder]
 AudioHardware::AudioHardware() :
 ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:611:37: warning: 'android_audio_legacy::AudioHardware::mOutput' will be initialized after [-Wreorder]
             AudioStreamOutMSM72xx\*  mOutput;
                                     ^
device/huawei/c8812e/audio/AudioHardware.h:609:25: warning:   'bool android_audio_legacy::AudioHardware::mBluetoothVGS' [-Wreorder]
             bool        mBluetoothVGS;
                         ^
device/huawei/c8812e/audio/AudioHardware.cpp:151:1: warning:   when initialized here [-Wreorder]
 AudioHardware::AudioHardware() :
 ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:629:25: warning: 'android_audio_legacy::AudioHardware::mDualMicEnabled' will be initialized after [-Wreorder]
             bool        mDualMicEnabled;
                         ^
device/huawei/c8812e/audio/AudioHardware.h:605:25: warning:   'int android_audio_legacy::AudioHardware::mFmFd' [-Wreorder]
             int         mFmFd;
                         ^
device/huawei/c8812e/audio/AudioHardware.cpp:151:1: warning:   when initialized here [-Wreorder]
 AudioHardware::AudioHardware() :
 ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:634:18: warning: 'android_audio_legacy::AudioHardware::mVoipOutActive' will be initialized after [-Wreorder]
             bool mVoipOutActive;
                  ^
device/huawei/c8812e/audio/AudioHardware.h:613:36: warning:   'android_audio_legacy::AudioHardware::AudioStreamOutDirect\* android_audio_legacy::AudioHardware::mDirectOutput' [-Wreorder]
             AudioStreamOutDirect\*  mDirectOutput;
                                    ^
device/huawei/c8812e/audio/AudioHardware.cpp:151:1: warning:   when initialized here [-Wreorder]
 AudioHardware::AudioHardware() :
 ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:278:17: warning: unused parameter 'flags' [-Wunused-parameter]
 AudioStreamOut\* AudioHardware::openOutputStreamWithFlags(uint32_t devices,
                 ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'virtual android_audio_legacy::AudioStreamOut\* android_audio_legacy::AudioHardware::openOutputStream(uint32_t, int_, uint32_t_, uint32_t_, android::status_t_)':
device/huawei/c8812e/audio/AudioHardware.cpp:312:70: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioStreamOutDirect'
                 AudioStreamOutDirect\* out = new AudioStreamOutDirect();
                                                                      ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:323:11: note:   because the following virtual functions are pure within 'android_audio_legacy::AudioHardware::AudioStreamOutDirect':
     class AudioStreamOutDirect : public AudioStreamOut {
           ^
In file included from hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareBase.h:20:0,
                 from device/huawei/c8812e/audio/AudioHardware.h:29,
                 from device/huawei/c8812e/audio/AudioHardware.cpp:35:
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:116:25: note:  virtual android::status_t android_audio_legacy::AudioStreamOut::getPresentationPosition(uint64_t_, timespec_)
     virtual status_t    getPresentationPosition(uint64_t _frames, struct timespec *timestamp) = 0;
                         ^
device/huawei/c8812e/audio/AudioHardware.cpp:350:114: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioSessionOutLPA'
             AudioSessionOutLPA_ out = new AudioSessionOutLPA(this, devices, _format, *channels,_sampleRate,0,&err);
                                                                                                                  ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:363:7: note:   because the following virtual functions are pure within 'android_audio_legacy::AudioHardware::AudioSessionOutLPA':
 class AudioSessionOutLPA : public AudioStreamOut
       ^
In file included from hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareBase.h:20:0,
                 from device/huawei/c8812e/audio/AudioHardware.h:29,
                 from device/huawei/c8812e/audio/AudioHardware.cpp:35:
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:116:25: note:  virtual android::status_t android_audio_legacy::AudioStreamOut::getPresentationPosition(uint64_t_, timespec_)
     virtual status_t    getPresentationPosition(uint64_t _frames, struct timespec *timestamp) = 0;
                         ^
device/huawei/c8812e/audio/AudioHardware.cpp:372:68: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioStreamOutMSM72xx'
             AudioStreamOutMSM72xx_ out = new AudioStreamOutMSM72xx();
                                                                    ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h:270:11: note:   because the following virtual functions are pure within 'android_audio_legacy::AudioHardware::AudioStreamOutMSM72xx':
     class AudioStreamOutMSM72xx : public AudioStreamOut {
           ^
In file included from hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareBase.h:20:0,
                 from device/huawei/c8812e/audio/AudioHardware.h:29,
                 from device/huawei/c8812e/audio/AudioHardware.cpp:35:
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:116:25: note:  virtual android::status_t android_audio_legacy::AudioStreamOut::getPresentationPosition(uint64_t_, timespec_)
     virtual status_t    getPresentationPosition(uint64_t _frames, struct timespec *timestamp) = 0;
                         ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'virtual android::status_t android_audio_legacy::AudioHardware::setParameters(const android::String8&)':
device/huawei/c8812e/audio/AudioHardware.cpp:674:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare](mCurSndDevice == SND_DEVICE_HEADSET))
                              ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:862:5: warning: unused parameter 'size' [-Wunused-parameter]
 int check_and_set_audpp_parameters(char *buf, int size)
     ^
device/huawei/c8812e/audio/AudioHardware.cpp: In function 'int android_audio_legacy::msm72xx_enable_postproc(bool)':
device/huawei/c8812e/audio/AudioHardware.cpp:1391:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(snd_device == SND_DEVICE_SPEAKER)
                      ^
device/huawei/c8812e/audio/AudioHardware.cpp:1396:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(snd_device == SND_DEVICE_HANDSET)
                      ^
device/huawei/c8812e/audio/AudioHardware.cpp:1401:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(snd_device == SND_DEVICE_HEADSET)
                      ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'virtual android::status_t android_audio_legacy::AudioHardware::setVoiceVolume(float)':
device/huawei/c8812e/audio/AudioHardware.cpp:1624:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((mCurSndDevice != -1) && ((mCurSndDevice == SND_DEVICE_TTY_HEADSET) || (mCurSndDevice == SND_DEVICE_TTY_VCO)))
                                                     ^
device/huawei/c8812e/audio/AudioHardware.cpp:1624:98: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((mCurSndDevice != -1) && ((mCurSndDevice == SND_DEVICE_TTY_HEADSET) || (mCurSndDevice == SND_DEVICE_TTY_VCO)))
                                                                                                  ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'android::status_t android_audio_legacy::AudioHardware::doAudioRouteOrMute(uint32_t)':
device/huawei/c8812e/audio/AudioHardware.cpp:1759:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare](device != mCurSndDevice)) {
                    ^
device/huawei/c8812e/audio/AudioHardware.cpp:1762:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     } else if (((mCurSndDevice == SND_DEVICE_FM_DIGITAL_STEREO_HEADSET) ||
                                   ^
device/huawei/c8812e/audio/AudioHardware.cpp:1763:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare](mCurSndDevice == SND_DEVICE_FM_DIGITAL_SPEAKER_PHONE)  ||
                           ^
device/huawei/c8812e/audio/AudioHardware.cpp:1764:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare](mCurSndDevice == SND_DEVICE_FM_DIGITAL_BT_A2DP_HEADSET)) &&
                           ^
device/huawei/c8812e/audio/AudioHardware.cpp:1765:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare](device != mCurSndDevice)) {
                    ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'android::status_t android_audio_legacy::AudioHardware::doRouting(android_audio_legacy::AudioHardware::AudioStreamInMSM72xx_)':
device/huawei/c8812e/audio/AudioHardware.cpp:1926:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (new_snd_device == SND_DEVICE_HANDSET) {
                               ^
device/huawei/c8812e/audio/AudioHardware.cpp:1929:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         } else if (new_snd_device == SND_DEVICE_SPEAKER) {
                                      ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:2030:10: warning: unused parameter 'args' [-Wunused-parameter]
 status_t AudioHardware::dumpInternals(int fd, const Vector<String16>& args)
          ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h: In constructor 'android_audio_legacy::AudioHardware::AudioStreamInVoip::AudioStreamInVoip()':
device/huawei/c8812e/audio/AudioHardware.h:594:29: warning: 'android_audio_legacy::AudioHardware::AudioStreamInVoip::mDevices' will be initialized after [-Wreorder]
                 uint32_t    mDevices;
                             ^
device/huawei/c8812e/audio/AudioHardware.h:582:29: warning:   'bool android_audio_legacy::AudioHardware::AudioStreamInVoip::mSetupDevice' [-Wreorder]
                 bool        mSetupDevice;
                             ^
device/huawei/c8812e/audio/AudioHardware.cpp:2119:1: warning:   when initialized here [-Wreorder]
 AudioHardware::AudioStreamInVoip::AudioStreamInVoip() :
 ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'android::status_t android_audio_legacy::AudioHardware::AudioStreamInVoip::set(android_audio_legacy::AudioHardware_, uint32_t, int_, uint32_t_, uint32_t_, android_audio_legacy::AudioSystem::audio_in_acoustics)':
device/huawei/c8812e/audio/AudioHardware.cpp:2134:71: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((pFormat == 0) || BAD_INDEX == hw->getMvsMode(_pFormat, *pRate)) {
                                                                       ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:2128:10: warning: unused parameter 'acoustic_flags' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamInVoip::set(
          ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'virtual ssize_t android_audio_legacy::AudioHardware::AudioStreamInVoip::read(void_, ssize_t)':
device/huawei/c8812e/audio/AudioHardware.cpp:2307:34: warning: pointer of type 'void _' used in arithmetic [-Wpointer-arith]
                    memcpy(buffer+totalBytesRead, &audio_mvs_frame.voc_pkt, mBufferSize);
                                  ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:2358:10: warning: unused parameter 'args' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamInVoip::dump(int fd, const Vector<String16>& args)
          ^
device/huawei/c8812e/audio/AudioHardware.cpp:2602:10: warning: unused parameter 'args' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamOutMSM72xx::dump(int fd, const Vector<String16>& args)
          ^
device/huawei/c8812e/audio/AudioHardware.cpp:2691:10: warning: unused parameter 'dspFrames' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamOutMSM72xx::getRenderPosition(uint32_t *dspFrames)
          ^
In file included from device/huawei/c8812e/audio/AudioHardware.cpp:35:0:
device/huawei/c8812e/audio/AudioHardware.h: In constructor 'android_audio_legacy::AudioHardware::AudioStreamOutDirect::AudioStreamOutDirect()':
device/huawei/c8812e/audio/AudioHardware.h:352:29: warning: 'android_audio_legacy::AudioHardware::AudioStreamOutDirect::mStartCount' will be initialized after [-Wreorder]
                 int         mStartCount;
                             ^
device/huawei/c8812e/audio/AudioHardware.h:351:29: warning:   'int android_audio_legacy::AudioHardware::AudioStreamOutDirect::mRetryCount' [-Wreorder]
                 int         mRetryCount;
                             ^
device/huawei/c8812e/audio/AudioHardware.cpp:2698:1: warning:   when initialized here [-Wreorder]
 AudioHardware::AudioStreamOutDirect::AudioStreamOutDirect() :
 ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'android::status_t android_audio_legacy::AudioHardware::AudioStreamOutDirect::set(android_audio_legacy::AudioHardware_, uint32_t, int_, uint32_t_, uint32_t_)':
device/huawei/c8812e/audio/AudioHardware.cpp:2714:70: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((pFormat == 0) || BAD_INDEX == hw->getMvsMode(_pFormat, lRate)) {
                                                                      ^
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'virtual ssize_t android_audio_legacy::AudioHardware::AudioStreamOutDirect::write(const void_, size_t)':
device/huawei/c8812e/audio/AudioHardware.cpp:2857:34: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
         if(audio_mvs_frame.len < 0)
                                  ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:2905:10: warning: unused parameter 'args' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamOutDirect::dump(int fd, const Vector<String16>& args)
          ^
device/huawei/c8812e/audio/AudioHardware.cpp:2980:10: warning: unused parameter 'dspFrames' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamOutDirect::getRenderPosition(uint32_t *dspFrames)
          ^
device/huawei/c8812e/audio/AudioHardware.cpp:3000:10: warning: unused parameter 'acoustic_flags' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamInMSM72xx::set(
          ^
device/huawei/c8812e/audio/AudioHardware.cpp: In constructor 'android_audio_legacy::AudioHardware::AudioSessionOutLPA::AudioSessionOutLPA(android_audio_legacy::AudioHardware_, uint32_t, int, uint32_t, uint32_t, int, android::status_t_)':
device/huawei/c8812e/audio/AudioHardware.cpp:3398:25: warning: converting to non-pointer type 'pthread_t {aka long int}' from NULL [-Wconversion-null]
     mEventThread        = NULL;
                         ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:3366:1: warning: unused parameter 'devices' [-Wunused-parameter]
 AudioHardware::AudioSessionOutLPA::AudioSessionOutLPA( AudioHardware *hw,
 ^
device/huawei/c8812e/audio/AudioHardware.cpp:3366:1: warning: unused parameter 'type' [-Wunused-parameter]
device/huawei/c8812e/audio/AudioHardware.cpp:3565:10: warning: unused parameter 'fd' [-Wunused-parameter]
 status_t AudioHardware::AudioSessionOutLPA::dump(int fd, const Vector<String16>& args)
          ^
device/huawei/c8812e/audio/AudioHardware.cpp:3565:10: warning: unused parameter 'args' [-Wunused-parameter]
In file included from system/core/include/cutils/log.h:1:0,
                 from system/core/include/utils/Log.h:31,
                 from device/huawei/c8812e/audio/AudioHardware.cpp:22:
device/huawei/c8812e/audio/AudioHardware.cpp: In member function 'virtual android::status_t android_audio_legacy::AudioHardware::AudioSessionOutLPA::setVolume(float, float)':
system/core/include/log/log.h:505:39: warning: format '%f' expects argument of type 'double', but argument 4 has type 'long int' [-Wformat=]
     **android_log_print(prio, tag, fmt)
                                       ^
system/core/include/log/log.h:440:5: note: in expansion of macro 'android_printLog'
     android_printLog(priority, tag, __VA_ARGS**)
     ^
system/core/include/log/log.h:432:5: note: in expansion of macro 'LOG_PRI'
     LOG_PRI(ANDROID_##priority, tag, **VA_ARGS**)
     ^
system/core/include/log/log.h:76:29: note: in expansion of macro 'ALOG'
 #define **ALOGV(...) ((void)ALOG(LOG_VERBOSE, LOG_TAG, __VA_ARGS**))
                             ^
system/core/include/log/log.h:78:34: note: in expansion of macro '**ALOGV'
 #define ALOGV(...) do { if (0) { __ALOGV(__VA_ARGS**); } } while (0)
                                  ^
device/huawei/c8812e/audio/AudioHardware.cpp:3590:5: note: in expansion of macro 'ALOGV'
     ALOGV("LPA volume set (%f) succeeded",vol);
     ^
device/huawei/c8812e/audio/AudioHardware.cpp: At global scope:
device/huawei/c8812e/audio/AudioHardware.cpp:4061:10: warning: unused parameter 'dspFrames' [-Wunused-parameter]
 status_t AudioHardware::AudioSessionOutLPA::getRenderPosition(uint32_t *dspFrames)
          ^
device/huawei/c8812e/audio/AudioHardware.cpp:4245:10: warning: unused parameter 'args' [-Wunused-parameter]
 status_t AudioHardware::AudioStreamInMSM72xx::dump(int fd, const Vector<String16>& args)
          ^
build/core/binary.mk:617: recipe for target '/media/sunny/Android/L/out/target/product/c8812e/obj/SHARED_LIBRARIES/audio.primary.msm7x27a_intermediates/AudioHardware.o' failed
make: *_\* [/media/sunny/Android/L/out/target/product/c8812e/obj/SHARED_LIBRARIES/audio.primary.msm7x27a_intermediates/AudioHardware.o] Error 1
make: **\* waiting for unfinished job....

**Comment by fonz93** [comment]
i got that error too on recents builds, it's probably due to this commit

https://github.com/CyanogenMod/android_hardware_libhardware_legacy/commit/b6caca55f1cdc275324952e029df196b0d245b29

There are several fixes online, we have do add them to our device tree

this commit should match our device: https://github.com/HtcLegacy/android_device_htc_msm7x27a-common/commit/4500bbc05f58824e7d8c7d6497d80ee6d116690c

u8833 uses AudioHardware_cad.cpp, but looking at the Android.mk, u8825 uses AudioHardware.cpp

**Comment by chil360** [comment]
Fonz is corect, the libhardware_legacy commit causes this error. This build error only applies to CM12 as it has not been merged to SlimLP (yet?).

The fix from HTCLegacy can easily be adapted for the u8833 and u8825 audio hals.

For CM12, someone needs to publish and maintain device repos so we can add fixes like this that are specific to that rom.

**Comment by gregor160300** [comment]
I will try to change it to u8833 CM12, and I am planning on maintaining cm12 device repo for u8833

**Comment by sunnyden** [comment]
The problem is solved by replacing auidohardware.cpp.Thanks a lot :)
